final List<Map<String, dynamic>> products = [
  {
    "image": "assets/images/1.png",
    "title": "Sandal",
    "description": "Stylish and comfortable everyday footwear",
    "price": 18,
    "rating": 3.0,
    "discount": "-15%",
  },
  {
    "image": "assets/images/2.png",
    "title": "Watch",
    "description": "Elegant watch for a modern look",
    "price": 15,
    "rating": 4.0,
    "discount": "-20%",
  },
  {
    "image": "assets/images/3.png",
    "title": "Bag",
    "description": "Trendy bag with spacious storage",
    "price": 20,
    "rating": 5.0,
    "discount": "-10%",
  },
  {
    "image": "assets/images/4.png",
    "title": "Vanity",
    "description": "Compact vanity for everyday essentials",
    "price": 10,
    "rating": 4.0,
    "discount": "-25%",
  },
  {
    "image": "assets/images/5.png",
    "title": "Pink Bag",
    "description": "Cute pink bag with stylish design",
    "price": 13,
    "rating": 3.0,
    "discount": "-15%",
  },
  {
    "image": "assets/images/1.png",
    "title": "Heel",
    "description": "Elegant heels for a stylish look",
    "price": 18,
    "rating": 3.0,
    "discount": "-30%",
  },
  {
    "image": "assets/images/7.png",
    "title": "Smart Watch",
    "description": "Smart features with stylish modern design",
    "price": 13,
    "rating": 3.0,
    "discount": "-20%",
  },
];
